import {
  type Citation,
  type DailyReport,
  DailyReportSchema,
} from "@ai-cfo/agent";
import { formatPct, trendArrow } from "./format";

const citationLabel = (c: Citation): string => {
  if (c.kind === "snapshot") {
    return `snapshot ${c.snapshot_id}`;
  }
  if (c.kind === "anomaly") {
    return `anomaly ${c.anomaly_id}`;
  }
  if (c.kind === "flag") {
    return `flag ${c.flag_id}`;
  }
  return `memory ${c.memory_id}`;
};

const citationId = (c: Citation): string => {
  if (c.kind === "snapshot") {
    return c.snapshot_id;
  }
  if (c.kind === "anomaly") {
    return c.anomaly_id;
  }
  if (c.kind === "flag") {
    return c.flag_id;
  }
  return c.memory_id;
};

// biome-ignore lint/complexity/noExcessiveCognitiveComplexity: end-to-end markdown emitter — splitting per-section helpers loses the reading order
export const toMarkdown = (raw: DailyReport): string => {
  // Day-3 strict gate: refuse to render anything that doesn't pass the
  // canonical Zod schema. The renderer never gets to ship malformed reports.
  const report = DailyReportSchema.parse(raw);

  const lines: string[] = [];
  lines.push(`# Daily report — ${report.date}`);
  lines.push("");
  lines.push(
    `## ${report.headline.metric}: ${report.headline.value} ${trendArrow(report.headline.trend)} ${formatPct(report.headline.delta_pct)}`
  );
  lines.push("");
  lines.push(report.summary);
  lines.push("");

  if (report.top_movers.length > 0) {
    lines.push("## Top movers");
    for (const m of report.top_movers) {
      lines.push(
        `- **${m.metric}** ${m.value} (${formatPct(m.delta_pct)} vs prior) — ${m.narrative}`
      );
    }
    lines.push("");
  }

  if (report.flags.length > 0) {
    lines.push("## Reconciliation flags");
    for (const f of report.flags) {
      lines.push(`- **${f.kind}** [${f.severity}] — ${f.narrative}`);
    }
    lines.push("");
  }

  if (report.actions.length > 0) {
    lines.push("## Recommended actions");
    for (const a of report.actions) {
      const lock = a.irreversible ? " 🔒" : "";
      lines.push(`- **${a.title}**${lock} — ${a.reasoning}`);
    }
    lines.push("");
  }

  if (report.sync_health.length > 0) {
    lines.push("## Sync health");
    for (const s of report.sync_health) {
      lines.push(`- ${s.source}: ${s.status} (last sync ${s.last_synced_at})`);
    }
    lines.push("");
  }

  // References — every citation collected and listed.
  const refs = new Map<string, Citation>();
  const addCitation = (c: Citation) => refs.set(citationId(c), c);
  addCitation({
    kind: "snapshot",
    snapshot_id: report.headline.citation.snapshot_id,
  });
  for (const m of report.top_movers) {
    for (const c of m.citations) {
      addCitation(c);
    }
  }
  for (const f of report.flags) {
    addCitation({ kind: "flag", flag_id: f.citation.flag_id });
  }
  for (const a of report.actions) {
    for (const c of a.citations) {
      addCitation(c);
    }
  }

  if (refs.size > 0) {
    lines.push("## References");
    for (const c of refs.values()) {
      lines.push(`- ${citationLabel(c)}`);
    }
    lines.push("");
  }

  lines.push(
    `<sub>Generated by AI Operating CFO • ${report.metadata.model} • prompt ${report.metadata.prompt_version} • trace ${report.metadata.trace_id}</sub>`
  );
  return lines.join("\n");
};
