import { type DailyReport, DailyReportSchema } from "@ai-cfo/agent";
import type { KnownBlock } from "@slack/types";
import { formatPct, severityEmoji, trendArrow } from "./format";

export const toSlackBlocks = (raw: DailyReport): KnownBlock[] => {
  const report = DailyReportSchema.parse(raw);
  const blocks: KnownBlock[] = [];

  blocks.push({
    type: "header",
    text: { type: "plain_text", text: `Daily report — ${report.date}` },
  });

  blocks.push({
    type: "section",
    text: {
      type: "mrkdwn",
      text: `*${report.headline.metric}*: ${report.headline.value} ${trendArrow(report.headline.trend)} ${formatPct(report.headline.delta_pct)}\n${report.summary}`,
    },
  });

  if (report.top_movers.length > 0) {
    blocks.push({ type: "divider" });
    for (const m of report.top_movers) {
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*${m.metric}* ${m.value} (${formatPct(m.delta_pct)})\n${m.narrative}`,
        },
      });
    }
  }

  if (report.flags.length > 0) {
    blocks.push({ type: "divider" });
    for (const f of report.flags) {
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `${severityEmoji(f.severity)} *${f.kind}* — ${f.narrative}`,
        },
      });
    }
  }

  if (report.actions.length > 0) {
    blocks.push({ type: "divider" });
    for (const a of report.actions) {
      const lock = a.irreversible ? " 🔒" : "";
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*${a.title}*${lock}\n${a.reasoning}`,
        },
      });
    }
  }

  blocks.push({ type: "divider" });
  blocks.push({
    type: "actions",
    elements: [
      {
        type: "button",
        text: { type: "plain_text", text: "👍 Helpful" },
        action_id: `feedback_positive_${report.metadata.trace_id}`,
        style: "primary",
      },
      {
        type: "button",
        text: { type: "plain_text", text: "👎 Off-base" },
        action_id: `feedback_negative_${report.metadata.trace_id}`,
      },
      {
        type: "button",
        text: { type: "plain_text", text: "💬 Tell me why" },
        action_id: `feedback_correction_${report.metadata.trace_id}`,
      },
    ],
  });

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `Generated by AI Operating CFO • ${report.metadata.model} • ${report.metadata.generated_at}`,
      },
    ],
  });

  return blocks;
};
